name: pandamon
services:
  db:
    container_name: db
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: